In [1]:
import numpy as np

1. Array Creation:

Create a 1-dimensional array of integers from 1 to 10.

In [2]:
a=np.array(range(1,11))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a 2-dimensional array with random float values of shape (3, 4).

In [3]:
a=np.random.rand(3,4)
a

array([[0.85742419, 0.30243078, 0.33679374, 0.47797361],
       [0.24959343, 0.44121569, 0.92396062, 0.51301273],
       [0.25400589, 0.55821534, 0.17253838, 0.94453888]])

Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [4]:
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

2. Array Operations:

Given two 1-dimensional arrays, perform element-wise addition,
subtraction, multiplication, and division.

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
d=b-a
e=a*b
f=a/b
print(c)
print(d)
print(e)
print(f)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Calculate the mean, median, and standard deviation of a given 1-
dimensional array.

In [7]:
a=np.array([1,2,3])
b=np.mean(a)
c=np.median(a)
d=np.std(a)
print(b)
print(c)
print(d)

2.0
2.0
0.816496580927726


Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
4).

In [10]:
a=np.array(range(1,13))
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

3. Array Indexing and Slicing:

Extract the first row and last column of a 2-dimensional array.

In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])
print(a[:,-1])

[1 2 3]
[3 6 9]


Reverse the order of elements in a 1-dimensional array.

In [13]:
a=np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).

In [15]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=[x for x in a.flatten() if x%2==0]
b

[2, 4, 6, 8]

4. Array Broadcasting:

Add a scalar value to each element of a 2-dimensional array.

In [16]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a+10
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.

In [17]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([10,11,12])
c=a*b
c

array([[ 10,  22,  36],
       [ 40,  55,  72],
       [ 70,  88, 108]])

Linear Algebra:
Calculate the dot product of two 1-dimensional arrays.

In [18]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

Compute the matrix multiplication of two 2-dimensional arrays.

In [19]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

Find the inverse and determinant of a square matrix.

In [21]:
d=np.linalg.det(a)
d

-2.0000000000000004

In [22]:
e=np.linalg.inv(a)
e

array([[-2. ,  1. ],
       [ 1.5, -0.5]])